language: generic
sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD) # determine the current commit SHA, to be used in docker tagging (deploy.sh)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # disable prompts in google cloud CLI
before_install:
  - openssl aes-256-cbc -K $encrypted_227a26790598_key -iv $encrypted_227a26790598_iv -in gcloud-service-account.json.enc -out gcloud-service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file gcloud-service-account.json

  # these set of commands are also used in gcloud console configuration
  - gcloud config set project	multi-k8s-318516
  - gcloud config set compute/zone asia-southeast1-a
  - gcloud container clusters get-credentials multi-cluster # 'multi-cluster' is the name of our created cluster in gcloud

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t aambayec/client-test -f ./client/Dockerfile.dev ./client # 'aambayec/client-test' can be any name, it is important for tagging it for reference below

script:
  - docker run -e CI=true aambayec/client-test npm test

deploy:
  provider: script # create custom provider
  script: bash ./deploy.sh
  on:
    branch: master
