language: generic
sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_227a26790598_key -iv $encrypted_227a26790598_iv -in gcloud-service-account.json.enc -out gcloud-service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file gcloud-service-account.json
