apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: devtoc-com-tls
spec:
  secretName: devtoc-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: devtoc.com
  dnsNames:
    - devtoc.com
    - www.devtoc.com
